### ISSUE TITLE
Dark Theme — solid black (optional) for background

### ISSUE THREAD

**Issue by Korb** [Exclude0122/xivpn#2]
Please consider adding a night theme to the Xi VPN.

Here's how application developers argue for using #000 as a background color:

Google Android 14:

> Dark Theme Screen / On some screens, Dark theme will use a solid black background which will help extend your battery life. After scheduling, Dark theme will be enabled when your screen is off.

Catima:

> Pure black background for dark theme (reduces battery usage on OLED displays).

F-Droid:

> Use pure black background in dark theme. Recommended only for OLED screens.

**Comment by Exclude0122** [comment]
Added
https://github.com/Exclude0122/xivpn/commit/ec9b7086191a64fe0fc8f3f0377fdabae8e26917
